name: pick_and_place

image_shape: [3, 480, 640]
dataset_path: data/pick_and_place/pick_and_place_data.zarr
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    img1:
      shape: ${task.image_shape}
      type: rgb
    img2:
      shape: ${task.image_shape}
      type: rgb
    # depth_1:
    #   shape: ${task.image_shape}
    #   type: depth
    # camera_3:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_4:
    #   shape: ${task.image_shape}
    #   type: rgb
    joint_pos:
      shape: [7]
      type: low_dim
    joint_vel:
      shape: [7]
      type: low_dim
    joint_torque:
      shape: [20, 7]
      type: low_dim
  action: 
    shape: [7]

env_runner:
  _target_: tactile_diffusion_policy.env_runner.pick_and_place_image_runner.PickAndPlaceImageRunner

dataset:
  _target_: tactile_diffusion_policy.dataset.pick_and_place_dataset.PickAndPlaceDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

